### ISSUE TITLE
Please add RSS/ATOM. Thank you!

### ISSUE THREAD

**Issue by ntoll** [anmeisel/our-friend-the-computer#1]
Hi :wave: 

Really enjoying your show. As a UK dev of a certain age, it's catnip ;-) (especially the episode on Prestel - such memories).

I notice you have an RSS feed here: https://feeds.buzzsprout.com/1923356.rss Took me a while to find it (I don't use the walled garden services you also link to: Spotify etc...). Could you please add this link to your website so others / Feedly et al find / can subscribe via RSS..?

Thank you.

Peace,

N.

**Comment by anmeisel** [comment]
Hi Nicholas,

This is great! I will definitely update it tomorrow - many thanks for the pull request!
The site is super basic and I have yet to link it to a CMS as well, something to work on in the next for weeks when I have a mo.
Glad to hear you're enjoying the show :) ! Means a lot.

Very best,
Ana
